modLoader = "javafml"
loaderVersion = "[${forge_version},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "createtransfer"
version = "${version}"
displayName = "Create: Transfer"
authors = "SerpensSolida"
description = '''
This mod adds a single block: Transmission Chain!

This block can be used to power belt in a cleaner way without using encased chain drive.
'''
logoFile = "icon.png"

[[dependencies.createtransfer]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtransfer]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.createtransfer]]
modId="create"
mandatory=true
versionRange="${create_version}"
ordering="NONE"
side="BOTH"