plugins {
    id 'com.gradleup.shadow'
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    shadowCommon // Don't use shadow from the shadow plugin because we don't want IDEA to index this.
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common
}

def generatedResources = file("../common/src/generated")
sourceSets {
    main {
        resources.srcDir generatedResources
    }
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath

    runs {
        data {
            data()
            programArgs "--server", "--client", "--mod", "createtransmission"
            programArgs "--output", generatedResources.absolutePath
        }
    }
}



repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {

    //forge("net.minecraftforge:forge:$minecraft_version-$forge_version")
    neoForge("net.neoforged:neoforge:$neoforge_version")

    modImplementation("dev.architectury:architectury-neoforge:$architectury_version")

    common(project(path: ":common", configuration: "namedElements")) { transitive = false }
    shadowCommon(project(path: ":common", configuration: "transformProductionNeoForge")) { transitive = false }

    //Create and its dependencies
    modImplementation("com.simibubi.create:create-$minecraft_version:$create_neoforge_version:slim") { transitive = false }
    modImplementation("com.tterrag.registrate:Registrate:$registrate_neoforge_version")
    modImplementation("net.createmod.ponder:Ponder-NeoForge-$minecraft_version:$ponder_neoforge_version")
    modCompileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-$minecraft_version:$flywheel_neoforge_version")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-neoforge-$minecraft_version:$flywheel_neoforge_version")

    // Development QOL
    modLocalRuntime("mezz.jei:jei-$minecraft_version-neoforge:$jei_version") { transitive = false }

}

processResources {
    // set up properties for filling into metadata
    Map<String, Object> properties = [
            "version": version,
            "neoforge_version": neoforge_version.split("\\.")[0], // only specify major version of forge
            "minecraft_version": minecraft_version,
            "create_version": create_neoforge_version.split("-")[0] // cut off build number
    ]
    inputs.properties(properties)

    filesMatching("META-INF/neoforge.mods.toml") {
        expand properties
    }
}

shadowJar {
    exclude "fabric.mod.json"
    exclude "architectury.common.json"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = null
}

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}

components.java {
    withVariantsFromConfiguration(project.configurations.shadowRuntimeElements) {
        skip()
    }
}
